CREATE PROC [dbo].[usp_UpdateCustomer]

	@Id bigint,
	@FirstName nvarchar(50),
	@MiddleName nvarchar(50),
	@LastName nvarchar(50),
	@Suffix nvarchar(50),
	@PrimaryEmail varchar(255),
	@PrimaryPhone varchar(50),
	@SecondaryEmail varchar(255),
	@SecondaryPhone varchar(50),
	@TitleId int,
	@Reference nvarchar(255),
	@AccountId bigint,
	@CreatedTimestamp datetime,
	@ModifiedTimestamp datetime,
	@EffectiveTimestamp datetime,
	@ActivationTimestamp datetime,
	@CancellationTimestamp datetime,
	@CompanyName nvarchar(255),
	@CurrencyId bigint,
	@MonthlyRecurringRevenue money,
	@SalesforceId nvarchar(255),
	@ActivationDay tinyint,
	@NetMRR money,
	@StatusId int,
	@AccountStatusId int,
	@ArBalance money,
	@NetsuiteId nvarchar(255),
	@NextBillingDate datetime,
	@NetsuiteEntityTypeId int,
	@SalesforceAccountTypeId tinyint,
	@SalesforceSynchStatusId tinyint,
	@QuickBooksId bigint,
	@QuickBooksLatchTypeId tinyint,
	@QuickBooksSyncToken bigint,
	@NetsuiteSynchStatusId tinyint
AS
SET NOCOUNT ON
	UPDATE [Customer] SET 
		[FirstName] = @FirstName,
		[MiddleName] = @MiddleName,
		[LastName] = @LastName,
		[Suffix] = @Suffix,
		[PrimaryEmail] = @PrimaryEmail,
		[PrimaryPhone] = @PrimaryPhone,
		[SecondaryEmail] = @SecondaryEmail,
		[SecondaryPhone] = @SecondaryPhone,
		[TitleId] = @TitleId,
		[Reference] = @Reference,
		[AccountId] = @AccountId,
		[CreatedTimestamp] = @CreatedTimestamp,
		[ModifiedTimestamp] = @ModifiedTimestamp,
		[EffectiveTimestamp] = @EffectiveTimestamp,
		[ActivationTimestamp] = @ActivationTimestamp,
		[CancellationTimestamp] = @CancellationTimestamp,
		[CompanyName] = @CompanyName,
		[CurrencyId] = @CurrencyId,
		[MonthlyRecurringRevenue] = @MonthlyRecurringRevenue,
		[SalesforceId] = @SalesforceId,
		[ActivationDay] = @ActivationDay,
		[NetMRR] = @NetMRR,
		[StatusId] = @StatusId,
		[AccountStatusId] = @AccountStatusId,
		[ArBalance] = @ArBalance,
		[NetsuiteId] = @NetsuiteId,
		[NextBillingDate] = @NextBillingDate,
		[NetsuiteEntityTypeId] = @NetsuiteEntityTypeId,
		[SalesforceAccountTypeId] = @SalesforceAccountTypeId,
		[SalesforceSynchStatusId] = @SalesforceSynchStatusId,
		[QuickBooksId] = @QuickBooksId,
		[QuickBooksLatchTypeId] = @QuickBooksLatchTypeId,
		[QuickBooksSyncToken] = @QuickBooksSyncToken,
		[NetsuiteSynchStatusId] = @NetsuiteSynchStatusId
	WHERE [Id] = @Id

SET NOCOUNT OFF

GO

