CREATE PROC [dbo].[usp_UpdateAccountInvoicePreference]

	@Id bigint,
	@NextInvoiceNumber int,
	@InvoiceSignature nvarchar(Max),
	@ShowShippingAddress bit,
	@InvoiceNote nvarchar(4000),
	@RollUpTaxes bit,
	@PurchaseLabel nvarchar(255),
	@ShowTrackedItemName bit,
	@ShowTrackedItemReference bit,
	@ShowTrackedItemDescription bit,
	@ShowTrackedItemCreatedDate bit,
	@TrackedItemDisplayFormatId int,
	@TrackedItemNameFieldOverride nvarchar(100),
	@TrackedItemReferenceFieldOverride nvarchar(100),
	@TrackedItemDescriptionFieldOverride nvarchar(100),	
	@TrackedItemCreatedDateFieldOverride nvarchar(100),
	@TrackedItemMainInvoiceMessage nvarchar(500),
	@TrackedItemPageLabelOverride nvarchar(100),
	@InvoiceCustomerReferenceOption int,
	@LayoutId int,
	@RollUpDiscounts bit,
	@ProjectedNotes nvarchar(4000),
	@ProjectedIncludeWatermark bit,
	@DraftInvoiceIncludeWatermark bit,
	@ShowServiceDates bit,
	@InvoiceSummarization bit,
	@PdfRollUpDisplayName bit,
	@PdfRollUpDisplayDescription bit,
	@PdfRollUpDisplayAllUnitPrices bit, 
	@PdfInvoiceEmailAttachmentOption tinyint,
	@InvoiceSummarizationOption tinyint,
	@ChargeGroupOrderId tinyint,
	@ShowPaymentDetails bit,
	@InvoiceIncludeWatermark bit
AS
SET NOCOUNT ON
	UPDATE [AccountInvoicePreference] SET 
		[NextInvoiceNumber] = @NextInvoiceNumber,
		[InvoiceSignature] = @InvoiceSignature,
		[ShowShippingAddress] = @ShowShippingAddress,
		[InvoiceNote] = @InvoiceNote,
		[RollUpTaxes] = @RollUpTaxes,
		[PurchaseLabel] = @PurchaseLabel,
		[TrackedItemDisplayFormatId] = @TrackedItemDisplayFormatId,
		[ShowTrackedItemName] = @ShowTrackedItemName,
		[ShowTrackedItemReference] = @ShowTrackedItemReference,
		[ShowTrackedItemDescription] = @ShowTrackedItemDescription,
		[ShowTrackedItemCreatedDate] = @ShowTrackedItemCreatedDate,
		[TrackedItemNameFieldOverride] = @TrackedItemNameFieldOverride,
		[TrackedItemReferenceFieldOverride] = @TrackedItemReferenceFieldOverride,
		[TrackedItemDescriptionFieldOverride] = @TrackedItemDescriptionFieldOverride,
		[TrackedItemCreatedDateFieldOverride] = @TrackedItemCreatedDateFieldOverride,
		[TrackedItemPageLabelOverride] = @TrackedItemPageLabelOverride,
		[TrackedItemMainInvoiceMessage] = @TrackedItemMainInvoiceMessage,
		[InvoiceCustomerReferenceOption] = @InvoiceCustomerReferenceOption,
		[LayoutId] = @LayoutId,
		[RollUpDiscounts] = @RollUpDiscounts,
		[ProjectedNotes] = @ProjectedNotes,
		[ProjectedIncludeWatermark] = @ProjectedIncludeWatermark,
		[DraftInvoiceIncludeWatermark] = @DraftInvoiceIncludeWatermark,
		[ShowServiceDates] = @ShowServiceDates,
		[InvoiceSummarization] = @InvoiceSummarization,
		[PdfRollUpDisplayName] = @PdfRollUpDisplayName,
		[PdfRollUpDisplayDescription] =	@PdfRollUpDisplayDescription,
		[PdfRollUpDisplayAllUnitPrices] = @PdfRollUpDisplayAllUnitPrices, 
		[PdfInvoiceEmailAttachmentOption] =	@PdfInvoiceEmailAttachmentOption,
		[InvoiceSummarizationOption] = @InvoiceSummarizationOption,
		[ChargeGroupOrderId] = @ChargeGroupOrderId,
		[ShowPaymentDetails] = @ShowPaymentDetails,
		[InvoiceIncludeWatermark] = @InvoiceIncludeWatermark
	WHERE [Id] = @Id

SET NOCOUNT OFF

GO

