
CREATE       PROC [dbo].[usp_UpdateSubscription] 
    @Id bigint,
    @CustomerId bigint,
    @CreatedTimestamp datetime,
    @ModifiedTimestamp datetime,
    @StatusId int,
    @PlanFrequencyId bigint,
    @ActivationTimestamp datetime = NULL,
    @CancellationTimestamp datetime = NULL,
    @ScheduledActivationTimestamp datetime = NULL,
    @ProvisionedTimestamp datetime = NULL,
    @RemainingInterval int = NULL,
    @InvoiceDay int,
    @Reference nvarchar(255) = NULL,
    @AutoApplyCatalogChanges bit,
    @MonthlyRecurringRevenue money,
    @Amount money,
    @SalesforceId nvarchar(255) = NULL,
    @ContractStartTimestamp datetime = NULL,
    @ContractEndTimestamp datetime = NULL,
    @NetMRR money,
    @NetsuiteId nvarchar(255) = NULL,
    @BillingPeriodDefinitionId bigint = NULL,
    @ExpiredTimestamp datetime = NULL,
    @PlanName nvarchar(100),
    @PlanCode nvarchar(255),
    @PlanDescription nvarchar(1000) = NULL,
    @PlanLongDescription nvarchar(4000) = NULL,
    @PlanReference nvarchar(255) = NULL,
    @PlanFrequencyUniqueId bigint,
    @PlanId bigint,
    @IntervalId int,
    @NumberOfIntervals int,
    @RemainingIntervalPushOut int = NULL,
    @CurrentMrr money,
    @CurrentNetMrr money,
    @MigratedTimestamp datetime = NULL,
    @InvoiceInAdvance tinyint,
    @HubSpotDealId bigint = NULL,
    @GeotabDevicePlanId NVARCHAR(255) = NULL,
	@QuickBooksClassId VARCHAR(50) = NULL,
	@RemainingRefreshPriceInterval INT = NULL,
	@RemainingRefreshPriceIntervalPushOut INT = NULL,
	@PriceWasRefreshedAtLastInterval BIT,
	@SourceSubscriptionId bigint = null,
	@InvoiceWeekday int = null,
	@AccountId bigint = null
AS 
	SET NOCOUNT ON

	UPDATE [dbo].[Subscription]
	SET    
	[CustomerId] = @CustomerId, 
	[CreatedTimestamp] = @CreatedTimestamp, 
	 --ModifiedTimestamp is used for the DW push, so rely on database time rather than provided time. 
	 --Causes less delay between the modified timestamp and the DB write,   
	 --and makes it less likely that the sliding SSIS window will miss the entity:
	[ModifiedTimestamp] = GETUTCDATE(),
	[StatusId] = @StatusId, 
	[PlanFrequencyId] = @PlanFrequencyId, 
	[ActivationTimestamp] = @ActivationTimestamp, 
	[CancellationTimestamp] = @CancellationTimestamp, 
	[ScheduledActivationTimestamp] = @ScheduledActivationTimestamp, 
	[ProvisionedTimestamp] = @ProvisionedTimestamp, 
	[RemainingInterval] = @RemainingInterval, 
	[InvoiceDay] = @InvoiceDay, 
	[Reference] = @Reference, 
	[AutoApplyCatalogChanges] = @AutoApplyCatalogChanges, 
	[MonthlyRecurringRevenue] = @MonthlyRecurringRevenue, 
	[Amount] = @Amount, 
	[SalesforceId] = @SalesforceId, 
	[ContractStartTimestamp] = @ContractStartTimestamp, 
	[ContractEndTimestamp] = @ContractEndTimestamp, 
	[NetMRR] = @NetMRR, 
	[NetsuiteId] = @NetsuiteId, 
	[BillingPeriodDefinitionId] = @BillingPeriodDefinitionId, 
	[ExpiredTimestamp] = @ExpiredTimestamp, 
	[PlanName] = @PlanName, 
	[PlanCode] = @PlanCode, 
	[PlanDescription] = @PlanDescription, 
	[PlanLongDescription] = @PlanLongDescription, 
	[PlanReference] = @PlanReference, 
	[PlanFrequencyUniqueId] = @PlanFrequencyUniqueId, 
	[PlanId] = @PlanId, 
	[IntervalId] = @IntervalId, 
	[NumberOfIntervals] = @NumberOfIntervals, 
	[RemainingIntervalPushOut] = @RemainingIntervalPushOut, 
	[CurrentMrr] = @CurrentMrr, 
	[CurrentNetMrr] = @CurrentNetMrr, 
	[MigratedTimestamp] = @MigratedTimestamp, 
	[InvoiceInAdvance] = @InvoiceInAdvance, 
	[HubSpotDealId] = @HubSpotDealId, 
	[GeotabDevicePlanId] = @GeotabDevicePlanId, 
	[QuickBooksClassId] = @QuickBooksClassId,
	[RemainingRefreshPriceInterval] = @RemainingRefreshPriceInterval, 
	[RemainingRefreshPriceIntervalPushOut] = @RemainingRefreshPriceIntervalPushOut,
	[PriceWasRefreshedAtLastInterval] = @PriceWasRefreshedAtLastInterval, 
	[SourceSubscriptionId] = @SourceSubscriptionId, 
	[InvoiceWeekday] = @InvoiceWeekday,
	[AccountId] = @AccountId
	WHERE  [Id] = @Id

	SET NOCOUNT OFF

GO

