CREATE PROC [dbo].[usp_UpdateSubscriptionProduct]

	@Id bigint,
	@CreatedTimestamp datetime,
	@ModifiedTimestamp datetime,
	@Included bit,
	@PlanProductId bigint,
	@Quantity decimal,
	@SubscriptionId bigint,
	@StartDate datetime,
	@ChargeAtSubscriptionActivation bit,
	@IsCharged bit,
	@IsTrackingItems bit,
	@MonthlyRecurringRevenue money,
	@Amount money,
	@StatusId int,
	@SalesforceId nvarchar(255),
	@NetMRR money,
	@MaxQuantity decimal,
	@IsFixed bit,
	@NetsuiteId nvarchar(255),
	@EarningTimingTypeId int,
	@EarningTimingIntervalId int,
	@PlanProductName nvarchar(100),
	@PlanProductDescription nvarchar(1000),
	@PlanProductCode nvarchar(1000),
	@PlanProductUniqueId bigint,
	@ProductId bigint,
	@ProductTypeId int,
	@IsRecurring bit,
	@IsOptional bit,
	@IsIncludedByDefault bit,
	@ResetTypeId int,
	@RecurChargeTimingTypeId int,
	@RecurProrateGranularityId int,
	@RecurProrateNegativeQuantity bit,
	@RecurProratePositiveQuantity bit,
	@RecurReverseChargeNegativeQuantity bit,
	@QuantityChargeTimingTypeId int,
	@QuantityProrateGranularityId int,
	@QuantityProrateNegativeQuantity bit,
	@QuantityProratePositiveQuantity bit,
	@QuantityReverseChargeNegativeQuantity bit,
	@PricingModelTypeId int,
	@IsEarnedImmediately bit,
	@EarningIntervalId int,
	@EarningNumberOfInterval int,
	@RemainingInterval int,
	@ExpiredTimestamp datetime
AS
SET NOCOUNT ON
	UPDATE [SubscriptionProduct] SET 
		[CreatedTimestamp] = @CreatedTimestamp,
		[ModifiedTimestamp] = @ModifiedTimestamp,
		[Included] = @Included,
		[PlanProductId] = @PlanProductId,
		[Quantity] = @Quantity,
		[SubscriptionId] = @SubscriptionId,
		[StartDate] = @StartDate,
		[ChargeAtSubscriptionActivation] = @ChargeAtSubscriptionActivation,
		[IsCharged] = @IsCharged,
		[IsTrackingItems] = @IsTrackingItems,
		[MonthlyRecurringRevenue] = @MonthlyRecurringRevenue,
		[Amount] = @Amount,
		[StatusId] = @StatusId,
		[SalesforceId] = @SalesforceId,
		[NetMRR] = @NetMRR,
		[MaxQuantity] = @MaxQuantity,
		[IsFixed] = @IsFixed,
		[NetsuiteId] = @NetsuiteId,
		[EarningTimingTypeId] = @EarningTimingTypeId,
		[EarningTimingIntervalId] = @EarningTimingIntervalId,
		[PlanProductName] = @PlanProductName,
		[PlanProductDescription] = @PlanProductDescription,
		[PlanProductCode] = @PlanProductCode,
		[PlanProductUniqueId] = @PlanProductUniqueId,
		[ProductId] = @ProductId,
		[ProductTypeId] = @ProductTypeId,
		[IsRecurring] = @IsRecurring,
		[IsOptional] = @IsOptional,
		[IsIncludedByDefault] = @IsIncludedByDefault,
		[ResetTypeId] = @ResetTypeId,
		[RecurChargeTimingTypeId] = @RecurChargeTimingTypeId,
		[RecurProrateGranularityId] = @RecurProrateGranularityId,
		[RecurProrateNegativeQuantity] = @RecurProrateNegativeQuantity,
		[RecurProratePositiveQuantity] = @RecurProratePositiveQuantity,
		[RecurReverseChargeNegativeQuantity] = @RecurReverseChargeNegativeQuantity,
		[QuantityChargeTimingTypeId] = @QuantityChargeTimingTypeId,
		[QuantityProrateGranularityId] = @QuantityProrateGranularityId,
		[QuantityProrateNegativeQuantity] = @QuantityProrateNegativeQuantity,
		[QuantityProratePositiveQuantity] = @QuantityProratePositiveQuantity,
		[QuantityReverseChargeNegativeQuantity] = @QuantityReverseChargeNegativeQuantity,
		[PricingModelTypeId] = @PricingModelTypeId,
		[IsEarnedImmediately] = @IsEarnedImmediately,
		[EarningIntervalId] = @EarningIntervalId,
		[EarningNumberOfInterval] = @EarningNumberOfInterval,
		[RemainingInterval] = @RemainingInterval,
		[ExpiredTimestamp] = @ExpiredTimestamp
	WHERE [Id] = @Id

SET NOCOUNT OFF

GO

