CREATE PROC [dbo].[usp_InsertCustomer]

	@FirstName nvarchar(50),
	@MiddleName nvarchar(50),
	@LastName nvarchar(50),
	@Suffix nvarchar(50),
	@PrimaryEmail varchar(255),
	@PrimaryPhone varchar(50),
	@SecondaryEmail varchar(255),
	@SecondaryPhone varchar(50),
	@TitleId int,
	@Reference nvarchar(255),
	@AccountId bigint,
	@CreatedTimestamp datetime,
	@ModifiedTimestamp datetime,
	@EffectiveTimestamp datetime,
	@ActivationTimestamp datetime,
	@CancellationTimestamp datetime,
	@CompanyName nvarchar(255),
	@CurrencyId bigint,
	@MonthlyRecurringRevenue money,
	@SalesforceId nvarchar(255),
	@ActivationDay tinyint,
	@NetMRR money,
	@StatusId int,
	@AccountStatusId int,
	@ArBalance money,
	@NetsuiteId nvarchar(255),
	@NextBillingDate datetime,
	@NetsuiteEntityTypeId int,
	@SalesforceAccountTypeId tinyint,
	@SalesforceSynchStatusId tinyint,
	@QuickBooksLatchTypeId tinyint,
	@QuickBooksId bigint,
	@QuickBooksSyncToken bigint,
	@NetsuiteSynchStatusId tinyint
AS
SET NOCOUNT ON
	INSERT INTO [Customer] (
		[FirstName],
		[MiddleName],
		[LastName],
		[Suffix],
		[PrimaryEmail],
		[PrimaryPhone],
		[SecondaryEmail],
		[SecondaryPhone],
		[TitleId],
		[Reference],
		[AccountId],
		[CreatedTimestamp],
		[ModifiedTimestamp],
		[EffectiveTimestamp],
		[ActivationTimestamp],
		[CancellationTimestamp],
		[CompanyName],
		[CurrencyId],
		[MonthlyRecurringRevenue],
		[SalesforceId],
		[ActivationDay],
		[NetMRR],
		[StatusId],
		[AccountStatusId],
		[ArBalance],
		[NetsuiteId],
		[NextBillingDate],
		[NetsuiteEntityTypeId],
		[SalesforceAccountTypeId],
		[SalesforceSynchStatusId],
		[QuickBooksId],
		[QuickBooksLatchTypeId],
		[QuickBooksSyncToken],
		[NetsuiteSynchStatusId]
	)
	VALUES (
		@FirstName,
		@MiddleName,
		@LastName,
		@Suffix,
		@PrimaryEmail,
		@PrimaryPhone,
		@SecondaryEmail,
		@SecondaryPhone,
		@TitleId,
		@Reference,
		@AccountId,
		@CreatedTimestamp,
		@ModifiedTimestamp,
		@EffectiveTimestamp,
		@ActivationTimestamp,
		@CancellationTimestamp,
		@CompanyName,
		@CurrencyId,
		@MonthlyRecurringRevenue,
		@SalesforceId,
		@ActivationDay,
		@NetMRR,
		@StatusId,
		@AccountStatusId,
		@ArBalance,
		@NetsuiteId,
		@NextBillingDate,
		@NetsuiteEntityTypeId,
		@SalesforceAccountTypeId,
		@SalesforceSynchStatusId,
		@QuickBooksId,
		@QuickBooksLatchTypeId,
		@QuickBooksSyncToken,
		@NetsuiteSynchStatusId
	)
	SELECT SCOPE_IDENTITY() As InsertedID
SET NOCOUNT OFF

GO

