 
 
CREATE PROC [dbo].[usp_InsertSubscriptionProduct]

	@CreatedTimestamp datetime,
	@ModifiedTimestamp datetime,
	@Included bit,
	@PlanProductId bigint,
	@Quantity decimal,
	@SubscriptionId bigint,
	@StartDate datetime,
	@ChargeAtSubscriptionActivation bit,
	@IsCharged bit,
	@IsTrackingItems bit,
	@MonthlyRecurringRevenue money,
	@Amount money,
	@StatusId int,
	@SalesforceId nvarchar(255),
	@NetMRR money,
	@MaxQuantity decimal,
	@IsFixed bit,
	@NetsuiteId nvarchar(255),
	@EarningTimingTypeId int,
	@EarningTimingIntervalId int,
	@PlanProductName nvarchar(100),
	@PlanProductDescription nvarchar(1000),
	@PlanProductCode nvarchar(1000),
	@PlanProductUniqueId bigint,
	@ProductId bigint,
	@ProductTypeId int,
	@IsRecurring bit,
	@IsOptional bit,
	@IsIncludedByDefault bit,
	@ResetTypeId int,
	@RecurChargeTimingTypeId int,
	@RecurProrateGranularityId int,
	@RecurProrateNegativeQuantity bit,
	@RecurProratePositiveQuantity bit,
	@RecurReverseChargeNegativeQuantity bit,
	@QuantityChargeTimingTypeId int,
	@QuantityProrateGranularityId int,
	@QuantityProrateNegativeQuantity bit,
	@QuantityProratePositiveQuantity bit,
	@QuantityReverseChargeNegativeQuantity bit,
	@PricingModelTypeId int,
	@IsEarnedImmediately bit,
	@EarningIntervalId int,
	@EarningNumberOfInterval int,
	@RemainingInterval int,
	@ExpiredTimestamp datetime
AS
SET NOCOUNT ON
	INSERT INTO [SubscriptionProduct] (
		[CreatedTimestamp],
		[ModifiedTimestamp],
		[Included],
		[PlanProductId],
		[Quantity],
		[SubscriptionId],
		[StartDate],
		[ChargeAtSubscriptionActivation],
		[IsCharged],
		[IsTrackingItems],
		[MonthlyRecurringRevenue],
		[Amount],
		[StatusId],
		[SalesforceId],
		[NetMRR],
		[MaxQuantity],
		[IsFixed],
		[NetsuiteId],
		[EarningTimingTypeId],
		[EarningTimingIntervalId],
		[PlanProductName],
		[PlanProductDescription],
		[PlanProductCode],
		[PlanProductUniqueId],
		[ProductId],
		[ProductTypeId],
		[IsRecurring],
		[IsOptional],
		[IsIncludedByDefault],
		[ResetTypeId],
		[RecurChargeTimingTypeId],
		[RecurProrateGranularityId],
		[RecurProrateNegativeQuantity],
		[RecurProratePositiveQuantity],
		[RecurReverseChargeNegativeQuantity],
		[QuantityChargeTimingTypeId],
		[QuantityProrateGranularityId],
		[QuantityProrateNegativeQuantity],
		[QuantityProratePositiveQuantity],
		[QuantityReverseChargeNegativeQuantity],
		[PricingModelTypeId],
		[IsEarnedImmediately],
		[EarningIntervalId],
		[EarningNumberOfInterval],
		[RemainingInterval],
		[ExpiredTimestamp]
	)
	VALUES (
		@CreatedTimestamp,
		@ModifiedTimestamp,
		@Included,
		@PlanProductId,
		@Quantity,
		@SubscriptionId,
		@StartDate,
		@ChargeAtSubscriptionActivation,
		@IsCharged,
		@IsTrackingItems,
		@MonthlyRecurringRevenue,
		@Amount,
		@StatusId,
		@SalesforceId,
		@NetMRR,
		@MaxQuantity,
		@IsFixed,
		@NetsuiteId,
		@EarningTimingTypeId,
		@EarningTimingIntervalId,
		@PlanProductName,
		@PlanProductDescription,
		@PlanProductCode,
		@PlanProductUniqueId,
		@ProductId,
		@ProductTypeId,
		@IsRecurring,
		@IsOptional,
		@IsIncludedByDefault,
		@ResetTypeId,
		@RecurChargeTimingTypeId,
		@RecurProrateGranularityId,
		@RecurProrateNegativeQuantity,
		@RecurProratePositiveQuantity,
		@RecurReverseChargeNegativeQuantity,
		@QuantityChargeTimingTypeId,
		@QuantityProrateGranularityId,
		@QuantityProrateNegativeQuantity,
		@QuantityProratePositiveQuantity,
		@QuantityReverseChargeNegativeQuantity,
		@PricingModelTypeId,
		@IsEarnedImmediately,
		@EarningIntervalId,
		@EarningNumberOfInterval,
		@RemainingInterval,
		@ExpiredTimestamp
	)
	SELECT SCOPE_IDENTITY() As InsertedID
SET NOCOUNT OFF

GO

