CREATE TABLE [Reporting].[AccountProfile] (
    [Account ID]                         BIGINT          NULL,
    [Company Name]                       NVARCHAR (255)  NULL,
    [Timezone]                           VARCHAR (255)   NULL,
    [Type]                               VARCHAR (50)    NULL,
    [Live]                               VARCHAR (5)     NULL,
    [Live Timestamp]                     VARCHAR (50)    NULL,
    [First Posted Invoice]               VARCHAR (50)    NULL,
    [Tax Option]                         VARCHAR (255)   NULL,
    [Currencies]                         INT             NULL,
    [Dunning Days]                       VARCHAR (255)   NULL,
    [Api Key]                            VARCHAR (50)    NULL,
    [Salesforce Enabled]                 VARCHAR (5)     NULL,
    [Netsuite Enabled]                   VARCHAR (5)     NULL,
    [Paypal Enabled]                     VARCHAR (5)     NULL,
    [Webhooks Enabled]                   VARCHAR (5)     NULL,
    [QuickBooks Enabled]                 VARCHAR (5)     NULL,
    [Coupons (Number of)]                INT             NULL,
    [Discounts]                          VARCHAR (5)     NULL,
    [Enabled Emails]                     INT             NULL,
    [Tracked Items]                      VARCHAR (5)     NULL,
    [Custom Fields (Number of)]          INT             NULL,
    [Sales Tracking Codes (Number of)]   INT             NULL,
    [Self Service Portal]                VARCHAR (5)     NULL,
    [Registration Pages]                 INT             NULL,
    [Custom Reports]                     INT             NULL,
    [Active Customers]                   INT             NULL,
    [Active Subscriptions]               INT             NULL,
    [Products Per Subscription]          INT             NULL,
    [Included Products Per Subscription] INT             NULL,
    [Avg Tracked Items Per Product]      INT             NULL,
    [Max Tracked Items Per Product]      INT             NULL,
    [Number Of Plans]                    INT             NULL,
    [Number Of Products]                 INT             NULL,
    [Data Weight]                        BIGINT          NULL,
    [User Count]                         INT             NULL,
    [Enabled User Count]                 INT             NULL,
    [Hubspot Configured]                 VARCHAR (5)     NULL,
    [Geotab Configured]                  VARCHAR (5)     NULL,
    [Transparent Redirect Enabled]       VARCHAR (5)     NULL,
    [Account Service Provider]           VARCHAR (255)   NULL,
    [Created Timestamp]                  VARCHAR (50)    NULL,
    [FusebillIncId]                      BIGINT          NULL,
    [NetMRR]                             VARCHAR (25)    NULL,
    [LifetimeValue]                      VARCHAR (25)    NULL,
    [MilestoneEarningEnabled]            VARCHAR (5)     NULL,
    [IsSalesforceActive]                 VARCHAR (5)     NULL,
    [PrimaryEmail]                       VARCHAR (255)   NULL,
    [CustomerStatus]                     VARCHAR (25)    NULL,
    [Id]                                 BIGINT          IDENTITY (1, 1) NOT NULL,
    [Website URL]                        NVARCHAR (255)  NULL,
    [Closure Date]                       DATETIME        NULL,
    [Closure Reason]                     NVARCHAR (1000) NULL,
    [Owner Name]                         NVARCHAR (1000) NULL,
    [Contact Name]                       NVARCHAR (1000) NULL,
    [Address line 1]                     NVARCHAR (255)  NULL,
    [Address line 2]                     NVARCHAR (255)  NULL,
    [City]                               NVARCHAR (255)  NULL,
    [Zip code]                           NVARCHAR (255)  NULL,
    [State]                              NVARCHAR (255)  NULL,
    [Country]                            NVARCHAR (255)  NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO

