CREATE TABLE [Lookup].[Country] (
    [Id]   BIGINT         NOT NULL,
    [Name] NVARCHAR (250) NOT NULL,
    [ISO]  VARCHAR (5)    NOT NULL,
    [ISO3] VARCHAR (6)    NOT NULL,
    CONSTRAINT [PK_Country] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (FILLFACTOR = 100, STATISTICS_NORECOMPUTE = ON)
);


GO

