CREATE TABLE [Lookup].[EntityType] (
    [Id]   INT           NOT NULL,
    [Name] VARCHAR (255) NOT NULL,
    CONSTRAINT [PK__lkEntityType] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (FILLFACTOR = 100, STATISTICS_NORECOMPUTE = ON)
);


GO

