CREATE TABLE [dbo].[AccountGeotabConfiguration] (
    [Id]                                                   BIGINT          NOT NULL,
    [StatusId]                                             TINYINT         NOT NULL,
    [GeotabAccountId]                                      VARCHAR (255)   NOT NULL,
    [Username]                                             NVARCHAR (100)  NOT NULL,
    [Password]                                             NVARCHAR (100)  NOT NULL,
    [Salt]                                                 NVARCHAR (100)  NOT NULL,
    [CreatedTimestamp]                                     DATETIME        NOT NULL,
    [ModifiedTimestamp]                                    DATETIME        NOT NULL,
    [ActivationTimestamp]                                  DATETIME        NULL,
    [SubscriptionActivation]                               BIT             DEFAULT ((0)) NOT NULL,
    [SubscriptionActivationField]                          VARCHAR (100)   NULL,
    [SubscriptionActivationIntervalId]                     TINYINT         NULL,
    [SubscriptionActivationDay]                            INT             NULL,
    [SubscriptionActivationHour]                           INT             NULL,
    [SubscriptionActivationLastRunTimestamp]               DATETIME        NULL,
    [SubscriptionActivationNextRunTimestamp]               DATETIME        NULL,
    [SubscriptionVinNumber]                                BIT             DEFAULT ((0)) NOT NULL,
    [SubscriptionVinNumberField]                           VARCHAR (100)   NULL,
    [SubscriptionVinNumberIntervalId]                      TINYINT         NULL,
    [SubscriptionVinNumberDay]                             INT             NULL,
    [SubscriptionVinNumberHour]                            INT             NULL,
    [SubscriptionVinNumberLastRunTimestamp]                DATETIME        NULL,
    [SubscriptionVinNumberNextRunTimestamp]                DATETIME        NULL,
    [SubscriptionCancel]                                   BIT             DEFAULT ((0)) NOT NULL,
    [SubscriptionCancelOption]                             INT             NULL,
    [SubscriptionCancelIntervalId]                         TINYINT         NULL,
    [SubscriptionCancelDay]                                INT             NULL,
    [SubscriptionCancelHour]                               INT             NULL,
    [SubscriptionCancelLastRunTimestamp]                   DATETIME        NULL,
    [SubscriptionCancelNextRunTimestamp]                   DATETIME        NULL,
    [SubscriptionActivationLeaveInDraft]                   BIT             CONSTRAINT [DF_AccountGeotabConfiguration_SubscriptionActivationLeaveInDraft] DEFAULT ((0)) NOT NULL,
    [SubscriptionCreate]                                   BIT             CONSTRAINT [DF_SubscriptionCreate] DEFAULT ((0)) NOT NULL,
    [SubscriptionCreateIntervalId]                         TINYINT         NULL,
    [SubscriptionCreateDay]                                INT             NULL,
    [SubscriptionCreateHour]                               INT             NULL,
    [SubscriptionCreateLastRunTimestamp]                   DATETIME        NULL,
    [SubscriptionCreateNextRunTimestamp]                   DATETIME        NULL,
    [SubscriptionActivationCheckDeviceActivationTimestamp] BIT             CONSTRAINT [DF_SubscriptionActivationCheckDeviceActivationTimestamp] DEFAULT ((0)) NOT NULL,
    [SubscriptionCreateFilterNoRatePlan]                   BIT             CONSTRAINT [DF_SubscriptionCreateFilterNoRatePlan] DEFAULT ((1)) NOT NULL,
    [SubscriptionCreateUsePromoCodes]                      BIT             CONSTRAINT [DF_SubscriptionCreateUsePromoCodes] DEFAULT ((0)) NOT NULL,
    [EncryptionVersion]                                    TINYINT         NOT NULL,
    [SubscriptionCreateDeviceTypeExcludeList]              NVARCHAR (1000) NULL,
    [SubscriptionCancelMatchToStandingOrders]              BIT             CONSTRAINT [DF_SubscriptionCancelMatchToStandingOrders] DEFAULT ((1)) NOT NULL,
    CONSTRAINT [PK_AccountGeotabConfig] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (FILLFACTOR = 100),
    CONSTRAINT [FK_AccountGeotabConfig_Account] FOREIGN KEY ([Id]) REFERENCES [dbo].[Account] ([Id]),
    CONSTRAINT [FK_AccountGeotabConfig_GeotabStatus] FOREIGN KEY ([StatusId]) REFERENCES [Lookup].[GeotabStatus] ([Id]),
    CONSTRAINT [FK_AccountGeotabConfiguration_CancelInterval] FOREIGN KEY ([SubscriptionCancelIntervalId]) REFERENCES [Lookup].[ReportInterval] ([Id]),
    CONSTRAINT [FK_AccountGeotabConfiguration_CancelOption] FOREIGN KEY ([SubscriptionCancelOption]) REFERENCES [Lookup].[SubscriptionCancellationReversalOptions] ([Id]),
    CONSTRAINT [FK_AccountGeotabConfiguration_CreateInterval] FOREIGN KEY ([SubscriptionCreateIntervalId]) REFERENCES [Lookup].[ReportInterval] ([Id]),
    CONSTRAINT [FK_AccountGeotabConfiguration_Interval] FOREIGN KEY ([SubscriptionActivationIntervalId]) REFERENCES [Lookup].[ReportInterval] ([Id]),
    CONSTRAINT [FK_AccountGeotabConfiguration_VinNumberInterval] FOREIGN KEY ([SubscriptionVinNumberIntervalId]) REFERENCES [Lookup].[ReportInterval] ([Id])
);


GO

