CREATE TABLE [dbo].[AccountNetsuiteConfiguration] (
    [Id]                                      BIGINT         NOT NULL,
    [StatusId]                                TINYINT        NOT NULL,
    [NetsuiteAccountId]                       VARCHAR (255)  NOT NULL,
    [TokenKey]                                NVARCHAR (255) NOT NULL,
    [TokenSecret]                             NVARCHAR (255) NOT NULL,
    [SaltKey]                                 NVARCHAR (100) NOT NULL,
    [SaltSecret]                              NVARCHAR (100) NOT NULL,
    [CreatedTimestamp]                        DATETIME       NOT NULL,
    [ModifiedTimestamp]                       DATETIME       NOT NULL,
    [ActivationTimestamp]                     DATETIME       NULL,
    [IsSandbox]                               BIT            DEFAULT ((0)) NOT NULL,
    [CustomerType]                            INT            DEFAULT ((0)) NOT NULL,
    [Subsidiary]                              NVARCHAR (50)  NOT NULL,
    [DefaultNetsuiteChargeItem]               VARCHAR (100)  NULL,
    [DefaultNetsuiteLocationId]               VARCHAR (100)  NULL,
    [DefaultNetsuiteChargeItemRecordType]     TINYINT        CONSTRAINT [DF_DefaultNetsuiteChargeItemRecordType] DEFAULT ((1)) NOT NULL,
    [DefaultNetsuiteClassId]                  VARCHAR (100)  NULL,
    [UseRevenueRecognition]                   BIT            CONSTRAINT [DF_UseRevenueRecognition] DEFAULT ((0)) NOT NULL,
    [DefaultNetsuiteRevenueStartDateId]       VARCHAR (255)  NULL,
    [DefaultNetsuiteRevenueEndDateId]         VARCHAR (255)  NULL,
    [AllowClassOverride]                      BIT            CONSTRAINT [DF_AllowClassOverride] DEFAULT ((0)) NOT NULL,
    [UseSha256Encryption]                     BIT            DEFAULT ((1)) NOT NULL,
    [MandatoryBins]                           BIT            CONSTRAINT [DF_MandatoryBins] DEFAULT ((0)) NOT NULL,
    [UseTaxPercentage]                        BIT            NOT NULL,
    [UseRefundTransaction]                    BIT            CONSTRAINT [DF_UseRefundTransaction] DEFAULT ((0)) NOT NULL,
    [SendQuantityWithCreditNotes]             BIT            CONSTRAINT [DF_SendQuantitityWithCreditNotes] DEFAULT ((0)) NOT NULL,
    [DefaultNetsuiteCreditItem]               VARCHAR (100)  NULL,
    [DefaultNetsuiteDiscountItem]             VARCHAR (100)  NULL,
    [DefaultNetsuiteWriteOffDebitLedgerItem]  VARCHAR (100)  NULL,
    [DefaultNetsuiteWriteOffCreditLedgerItem] VARCHAR (100)  NULL,
    [MapAddresses]                            BIT            CONSTRAINT [DF_AccountNetsuiteConfiguration_MapAddresses] DEFAULT ((0)) NOT NULL,
    [UseJournalsForWriteoffs]                 BIT            CONSTRAINT [DF_UseJournalsForWriteoffs] DEFAULT ((1)) NOT NULL,
    [CreditMemoStartDateBehaviorId]           TINYINT        CONSTRAINT [DF_CreditMemoStartDateBehaviorId_2] DEFAULT ((2)) NOT NULL,
    [UseDiscountLineItems]                    BIT            CONSTRAINT [DF_UseDiscountLineItems] DEFAULT ((1)) NOT NULL,
    CONSTRAINT [PK_AccountNetsuiteConfig] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (FILLFACTOR = 100),
    CONSTRAINT [FK_AccountNetsuiteConfig_Account] FOREIGN KEY ([Id]) REFERENCES [dbo].[Account] ([Id]),
    CONSTRAINT [FK_AccountNetsuiteConfig_DefaultNetsuiteChargeItemRecordType] FOREIGN KEY ([DefaultNetsuiteChargeItemRecordType]) REFERENCES [Lookup].[NetsuiteRecordType] ([Id]),
    CONSTRAINT [FK_AccountNetsuiteConfig_NetsuiteStatus] FOREIGN KEY ([StatusId]) REFERENCES [Lookup].[NetsuiteStatus] ([Id]),
    CONSTRAINT [FK_AccountNetsuiteConfiguration_CreditMemoStartDateBehaviorOption] FOREIGN KEY ([CreditMemoStartDateBehaviorId]) REFERENCES [Lookup].[CreditMemoStartDateBehaviorOption] ([Id]),
    CONSTRAINT [FK_AccountNetsuiteConfiguration_NetsuiteEntity] FOREIGN KEY ([CustomerType]) REFERENCES [Lookup].[NetsuiteEntityType] ([Id])
);


GO

