CREATE TABLE [dbo].[AccountQuickBooksOnlineConfig] (
    [Id]                       BIGINT         NOT NULL,
    [QuickBooksLatchTypeId]    TINYINT        CONSTRAINT [DF_AccountQuickBooksOnlineConfig_QuickBooksLatchTypeId] DEFAULT ((1)) NULL,
    [DisplayNameCompany]       BIT            CONSTRAINT [DF_AccountQuickBooksOnlineConfig_DisplayNameCompany] DEFAULT ((1)) NOT NULL,
    [DisplayNameFirstandLast]  BIT            CONSTRAINT [DF_AccountQuickBooksOnlineConfig_DisplayNameFirstandLast] DEFAULT ((1)) NOT NULL,
    [DisplayNameCustomerId]    BIT            CONSTRAINT [DF_AccountQuickBooksOnlineConfig_DisplayNameCustomerId] DEFAULT ((1)) NOT NULL,
    [ActivationTimeStamp]      DATETIME       NULL,
    [RealmId]                  VARCHAR (255)  NULL,
    [DataSource]               NVARCHAR (100) NULL,
    [Verifier]                 NVARCHAR (50)  NULL,
    [AccessToken]              VARCHAR (5000) NULL,
    [AccessTokenSecret]        VARCHAR (1000) NULL,
    [Salt]                     NVARCHAR (100) NULL,
    [MaintainDisplayName]      BIT            DEFAULT ((1)) NOT NULL,
    [IncomeAccountRefId]       BIGINT         NULL,
    [SalesItemRefId]           BIGINT         NULL,
    [RecognizeDiscounts]       BIT            DEFAULT ((0)) NOT NULL,
    [DiscountAccountRefId]     BIGINT         NULL,
    [CashAccountRefId]         BIGINT         NULL,
    [WriteOffAccountRefId]     BIGINT         NULL,
    [WriteOffItemRefId]        BIGINT         NULL,
    [CreditAccountRefId]       BIGINT         NULL,
    [CreditItemRefId]          BIGINT         NULL,
    [TaxAccountRefId]          BIGINT         NULL,
    [TaxItemRefId]             BIGINT         NULL,
    [TaxRecognitionOptionId]   TINYINT        CONSTRAINT [df_qbTaxRecognitionOptionId] DEFAULT ((1)) NOT NULL,
    [IsUsaCompany]             BIT            CONSTRAINT [df_QbIsUsaCompany] DEFAULT ((1)) NOT NULL,
    [TaxExemptCode]            VARCHAR (50)   NULL,
    [ExpirationTimestamp]      DATETIME       NOT NULL,
    [StatusId]                 TINYINT        NOT NULL,
    [OAuthVersion]             TINYINT        NOT NULL,
    [RedirectUrl]              NVARCHAR (100) NULL,
    [AccessTokenExpiry]        DATETIME       NULL,
    [ShouldRefreshToken]       BIT            NULL,
    [NotificationExpiryEmail]  BIT            CONSTRAINT [DF_NotificationExpiryEmail] DEFAULT ((0)) NOT NULL,
    [NotificationEmailRole]    BIGINT         NULL,
    [NotificationEmail]        VARCHAR (255)  NULL,
    [NotificationEmailSent]    BIT            CONSTRAINT [DF_NotificationEmailSent] DEFAULT ((0)) NOT NULL,
    [SendQuantity]             BIT            CONSTRAINT [DF_SendQuantity] DEFAULT ((0)) NOT NULL,
    [StaxBillBranding]         BIT            CONSTRAINT [DF_StaxBillBranding] DEFAULT ((1)) NOT NULL,
    [AllowClass]               BIT            CONSTRAINT [DF_AllowClass] DEFAULT ((0)) NOT NULL,
    [AllowLocation]            BIT            CONSTRAINT [DF_AllowLocation] DEFAULT ((0)) NOT NULL,
    [SendReferenceDate]        BIT            CONSTRAINT [DF_SendReferenceDate] DEFAULT ((0)) NOT NULL,
    [PaymentSendReferenceDate] BIT            CONSTRAINT [DF_PaymentSendReferenceDate_False] DEFAULT ((0)) NOT NULL,
    [SendInvoiceNumber]        BIT            CONSTRAINT [DF_SendInvoiceNumber_True] DEFAULT ((1)) NOT NULL,
    CONSTRAINT [PK_AccountQuickBooksOnlineConfig] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (FILLFACTOR = 100, STATISTICS_NORECOMPUTE = ON),
    CONSTRAINT [FK_AccountQuickBooksOnlineConfig_Account] FOREIGN KEY ([Id]) REFERENCES [dbo].[Account] ([Id]) ON DELETE CASCADE,
    CONSTRAINT [FK_AccountQuickBooksOnlineConfig_QuickBooksConfigurationStatus] FOREIGN KEY ([StatusId]) REFERENCES [Lookup].[QuickBooksConfigurationStatus] ([Id]),
    CONSTRAINT [FK_AccountQuickBooksOnlineConfig_QuickBooksTaxRecognitionOption] FOREIGN KEY ([TaxRecognitionOptionId]) REFERENCES [Lookup].[QuickBooksTaxRecognitionOption] ([Id]),
    CONSTRAINT [FK_AccountQuickBooksOnlineConfig_Role] FOREIGN KEY ([NotificationEmailRole]) REFERENCES [dbo].[Role] ([Id])
);


GO

