CREATE TABLE [dbo].[HostedPageManagedSelfServicePortal] (
    [HostedPageId]                         BIGINT         NOT NULL,
    [Id]                                   BIGINT         IDENTITY (1, 1) NOT NULL,
    [StatusTypeId]                         INT            NULL,
    [PrimaryFontColor]                     VARCHAR (10)   CONSTRAINT [df_PrimaryFontColor] DEFAULT ('#000000') NOT NULL,
    [PrimaryFontWeight]                    INT            CONSTRAINT [df_PrimaryFontWeight] DEFAULT ((400)) NOT NULL,
    [PrimaryBorderColor]                   VARCHAR (10)   CONSTRAINT [df_PrimaryBorderColor] DEFAULT ('#CFD8DC') NOT NULL,
    [PrimaryBorderRadius]                  INT            CONSTRAINT [df_PrimaryBorderRadius] DEFAULT ((2)) NOT NULL,
    [PrimaryLabelFontColor]                VARCHAR (10)   CONSTRAINT [df_PrimaryLabelFontColor] DEFAULT ('#546E7A') NOT NULL,
    [PrimaryLabelFontWeight]               INT            CONSTRAINT [df_PrimaryLabelFontWeight] DEFAULT ((600)) NOT NULL,
    [PrimaryButtonColor]                   VARCHAR (10)   CONSTRAINT [df_PrimaryButtonColor] DEFAULT ('#039BE5') NOT NULL,
    [PrimaryButtonHoverColor]              VARCHAR (10)   CONSTRAINT [df_PrimaryButtonHoverColor] DEFAULT ('#0288D1') NOT NULL,
    [PrimaryButtonFontColor]               VARCHAR (10)   CONSTRAINT [df_PrimaryButtonFontColor] DEFAULT ('#FFFFFF') NOT NULL,
    [PrimaryButtonFontHoverColor]          VARCHAR (10)   CONSTRAINT [df_PrimaryButtonFontHoverColor] DEFAULT ('#FFFFFF') NOT NULL,
    [NeutralButtonColor]                   VARCHAR (10)   CONSTRAINT [df_NeutralButtonColor] DEFAULT ('#ECEFF1') NOT NULL,
    [NeutralButtonHoverColor]              VARCHAR (10)   CONSTRAINT [df_NeutralButtonHoverColor] DEFAULT ('#CFD8DC') NOT NULL,
    [NeutralButtonFontColor]               VARCHAR (10)   CONSTRAINT [df_NeutralButtonFontColor] DEFAULT ('#263238') NOT NULL,
    [NeutralButtonFontHoverColor]          VARCHAR (10)   CONSTRAINT [df_NeutralButtonFontHoverColor] DEFAULT ('#263238') NOT NULL,
    [DisabledButtonColor]                  VARCHAR (10)   CONSTRAINT [df_DisabledButtonColor] DEFAULT ('#B0BEC5') NOT NULL,
    [DisabledButtonFontColor]              VARCHAR (10)   CONSTRAINT [df_DisabledButtonFontColor] DEFAULT ('#263238') NOT NULL,
    [HeaderLogoFileName]                   VARCHAR (500)  NULL,
    [HeaderLogoText]                       NVARCHAR (100) NULL,
    [HeaderLogoFontColor]                  VARCHAR (10)   CONSTRAINT [df_HeaderLogoFontColor] DEFAULT ('#546E7A') NOT NULL,
    [HeaderColor]                          VARCHAR (10)   CONSTRAINT [df_HeaderColor] DEFAULT ('#FFFFFF') NOT NULL,
    [HeaderMenuColor]                      VARCHAR (10)   CONSTRAINT [df_HeaderMenuColor] DEFAULT ('#039BE5') NOT NULL,
    [HeaderUsernameColor]                  VARCHAR (10)   CONSTRAINT [df_HeaderUsernameColor] DEFAULT ('#039BE5') NOT NULL,
    [NavigationItemColor]                  VARCHAR (10)   CONSTRAINT [df_NavigationItemColor] DEFAULT ('#FFFFFF') NOT NULL,
    [NavigationItemFontColor]              VARCHAR (10)   CONSTRAINT [df_NavigationItemFontColor] DEFAULT ('#263238') NOT NULL,
    [NavigationItemActiveColor]            VARCHAR (10)   CONSTRAINT [df_NavigationItemActiveColor] DEFAULT ('#039BE5') NOT NULL,
    [NavigationItemActiveFontColor]        VARCHAR (10)   CONSTRAINT [df_NavigationItemActiveFontColor] DEFAULT ('#FFFFFF') NOT NULL,
    [BreadcrumbColor]                      VARCHAR (10)   CONSTRAINT [df_BreadcrumbColor] DEFAULT ('#FFFFFF') NOT NULL,
    [BreadcrumbFontColor]                  VARCHAR (10)   CONSTRAINT [df_BreadcrumbFontColor] DEFAULT ('#263238') NOT NULL,
    [ContentColor]                         VARCHAR (10)   CONSTRAINT [df_ContentColor] DEFAULT ('#FFFFFF') NOT NULL,
    [ContentActionColor]                   VARCHAR (10)   CONSTRAINT [df_ContentActionColor] DEFAULT ('#FFFFFF') NOT NULL,
    [FooterColor]                          VARCHAR (10)   CONSTRAINT [df_FooterColor] DEFAULT ('#f5f6f7') NOT NULL,
    [FooterFontColor]                      VARCHAR (10)   CONSTRAINT [df_FooterFontColor] DEFAULT ('#263238') NOT NULL,
    [FooterTwitterInclude]                 BIT            CONSTRAINT [df_FooterTwitterInclude] DEFAULT ((0)) NOT NULL,
    [FooterTwitterHandle]                  NVARCHAR (100) NULL,
    [FooterLinkedInInclude]                BIT            CONSTRAINT [df_FooterLinkedInInclude] DEFAULT ((0)) NOT NULL,
    [FooterLinkedInHandle]                 NVARCHAR (100) NULL,
    [FooterYoutubeInclude]                 BIT            CONSTRAINT [df_FooterYoutubeInclude] DEFAULT ((0)) NOT NULL,
    [FooterYoutubeHandle]                  NVARCHAR (100) NULL,
    [FooterFacebookInclude]                BIT            CONSTRAINT [df_FooterFacebookInclude] DEFAULT ((0)) NOT NULL,
    [FooterFacebookHandle]                 NVARCHAR (100) NULL,
    [FooterIconColor]                      VARCHAR (10)   CONSTRAINT [df_FooterIconColor] DEFAULT ('#78909C') NOT NULL,
    [FooterIconHoverColor]                 VARCHAR (10)   CONSTRAINT [df_FooterIconHoverColor] DEFAULT ('#546E7A') NOT NULL,
    [FooterTermsInclude]                   BIT            CONSTRAINT [df_FooterTermsInclude] DEFAULT ((0)) NOT NULL,
    [FooterTermsUrl]                       VARCHAR (255)  NULL,
    [TemplateCardsAndModalsColor]          VARCHAR (10)   CONSTRAINT [df_TemplateCardsAndModalsColor] DEFAULT ('#eceff1') NOT NULL,
    [TemplateCardsAndModalsFontColor]      VARCHAR (10)   CONSTRAINT [df_TemplateCardsAndModalsFontColor] DEFAULT ('#263238') NOT NULL,
    [ContentBackLinkColor]                 VARCHAR (10)   CONSTRAINT [df_ContentBackLinkColor] DEFAULT ('#0000EE') NOT NULL,
    [TemplateCardsAndModalsHighlightColor] VARCHAR (10)   CONSTRAINT [DF_TemplateCardsAndModalsHighlightColor] DEFAULT ('#F57C00') NOT NULL,
    [HeaderLogoUseImageDimensions]         BIT            CONSTRAINT [DF_HeaderLogoUseImageDimensions] DEFAULT ((0)) NOT NULL,
    [SASS]                                 NVARCHAR (MAX) NULL,
    [ManagedCSS]                           NVARCHAR (MAX) NULL,
    [OfferingSASS]                         NVARCHAR (MAX) NULL,
    [OfferingCSS]                          NVARCHAR (MAX) NULL,
    [PurchaseNameLabel]                    NVARCHAR (100) CONSTRAINT [DF_PurchaseNameLabel] DEFAULT ('Add on extra purchase') NOT NULL,
    [PurchaseDescriptionLabel]             NVARCHAR (100) CONSTRAINT [DF_PurchaseDescriptionLabel] DEFAULT ('Description') NOT NULL,
    [PurchasePriceLabel]                   NVARCHAR (100) CONSTRAINT [DF_PurchasePriceLabel] DEFAULT ('Price') NOT NULL,
    [DescriptionOnSeparateLine]            BIT            CONSTRAINT [DF_DescriptionOnSeparateLine] DEFAULT ((0)) NOT NULL,
    [PaymentSuccessText]                   NVARCHAR (255) NULL,
    [HeaderLogoHeight]                     INT            CONSTRAINT [DF_HeaderLogoHeight] DEFAULT ((40)) NOT NULL,
    [ThemeId]                              BIGINT         CONSTRAINT [DF_HostedPageTheme] DEFAULT (NULL) NULL,
    CONSTRAINT [PK_HostedPageManagedSelfServicePortal] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (FILLFACTOR = 100),
    CONSTRAINT [FK_HostedPageManagedSelfServicePortal_HostedPage] FOREIGN KEY ([HostedPageId]) REFERENCES [dbo].[HostedPage] ([Id]) ON DELETE CASCADE,
    CONSTRAINT [FK_HostedPageManagedSelfServicePortal_HostedPageManagedSelfServicePortalStatusType] FOREIGN KEY ([StatusTypeId]) REFERENCES [Lookup].[HostedPageManagedSelfServicePortalStatusType] ([Id])
);


GO

CREATE NONCLUSTERED INDEX [IX_HostedPageManagedSelfServicePortal_HostedPageId]
    ON [dbo].[HostedPageManagedSelfServicePortal]([HostedPageId] ASC) WITH (FILLFACTOR = 100);


GO

