CREATE TABLE [dbo].[HostedPageManagedTheme] (
    [Id]                                   BIGINT         NOT NULL,
    [Name]                                 VARCHAR (255)  NOT NULL,
    [PrimaryFontColor]                     VARCHAR (100)  NULL,
    [PrimaryBorderColor]                   VARCHAR (100)  NULL,
    [PrimaryLabelFontColor]                VARCHAR (100)  NULL,
    [PrimaryButtonColor]                   VARCHAR (100)  NULL,
    [PrimaryButtonHoverColor]              VARCHAR (100)  NULL,
    [PrimaryButtonFontColor]               VARCHAR (100)  NULL,
    [PrimaryButtonFontHoverColor]          VARCHAR (100)  NULL,
    [NeutralButtonColor]                   VARCHAR (100)  NULL,
    [NeutralButtonHoverColor]              VARCHAR (100)  NULL,
    [NeutralButtonFontColor]               VARCHAR (100)  NULL,
    [NeutralButtonFontHoverColor]          VARCHAR (100)  NULL,
    [DisabledButtonColor]                  VARCHAR (100)  NULL,
    [DisabledButtonFontColor]              VARCHAR (100)  NULL,
    [HeaderLogoFontColor]                  VARCHAR (100)  NULL,
    [HeaderColor]                          VARCHAR (100)  NULL,
    [HeaderMenuColor]                      VARCHAR (100)  NULL,
    [HeaderUsernameColor]                  VARCHAR (100)  NULL,
    [NavigationItemColor]                  VARCHAR (100)  NULL,
    [NavigationItemFontColor]              VARCHAR (100)  NULL,
    [NavigationItemActiveColor]            VARCHAR (100)  NULL,
    [NavigationItemActiveFontColor]        VARCHAR (100)  NULL,
    [BreadcrumbColor]                      VARCHAR (100)  NULL,
    [BreadcrumbFontColor]                  VARCHAR (100)  NULL,
    [ContentColor]                         VARCHAR (100)  NULL,
    [ContentActionColor]                   VARCHAR (100)  NULL,
    [FooterColor]                          VARCHAR (100)  NULL,
    [FooterFontColor]                      VARCHAR (100)  NULL,
    [FooterIconColor]                      VARCHAR (100)  NULL,
    [FooterIconHoverColor]                 VARCHAR (100)  NULL,
    [TemplateCardsAndModalsColor]          VARCHAR (100)  NULL,
    [TemplateCardsAndModalsFontColor]      VARCHAR (100)  NULL,
    [ContentBackLinkColor]                 VARCHAR (100)  NULL,
    [TemplateCardsAndModalsHighlightColor] VARCHAR (100)  NULL,
    [Description]                          NVARCHAR (500) NULL,
    [Beta]                                 BIT            NOT NULL,
    CONSTRAINT [PK_HostedPageManagedTheme] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO

