CREATE TABLE [dbo].[HostedPageManagedOfferingLabel] (
    [Id]                                               BIGINT          NOT NULL,
    [PlanSelectionStepLabel]                           NVARCHAR (100)  NOT NULL,
    [PlanSelectionTitleLabel]                          NVARCHAR (100)  NULL,
    [PlanConfigurationStepVisible]                     BIT             CONSTRAINT [DF_PlanConfigurationStepVisible] DEFAULT ((0)) NOT NULL,
    [PlanConfigurationStepLabel]                       NVARCHAR (100)  NOT NULL,
    [PlanConfigurationTitleLabel]                      NVARCHAR (100)  NULL,
    [PlanConfigurationBackLabel]                       NVARCHAR (25)   NOT NULL,
    [PlanConfigurationNextLabel]                       NVARCHAR (25)   NOT NULL,
    [PlanProductTitleLabel]                            NVARCHAR (100)  NULL,
    [PlanProductDescriptionLabel]                      NVARCHAR (100)  NOT NULL,
    [PlanProductQuantityLabel]                         NVARCHAR (100)  NOT NULL,
    [PlanProductUnitPriceLabel]                        NVARCHAR (100)  NOT NULL,
    [PlanProductSubtotalLabel]                         NVARCHAR (100)  NULL,
    [PlanProductIncludedLabel]                         NVARCHAR (100)  NOT NULL,
    [PlanProductYesLabel]                              NVARCHAR (25)   NOT NULL,
    [PlanProductNoLabel]                               NVARCHAR (25)   NOT NULL,
    [CheckoutStepLabel]                                NVARCHAR (100)  NOT NULL,
    [CheckoutTitleLabel]                               NVARCHAR (100)  NULL,
    [CheckoutBackLabel]                                NVARCHAR (25)   NOT NULL,
    [CheckoutNextLabel]                                NVARCHAR (25)   NOT NULL,
    [TermsAndConditionLabel]                           NVARCHAR (100)  NOT NULL,
    [TermsAndConditionConfirmLabel]                    NVARCHAR (100)  NOT NULL,
    [TermsAndConditionLinkText]                        NVARCHAR (100)  NOT NULL,
    [PaymentMethodStepLabel]                           NVARCHAR (100)  NOT NULL,
    [PaymentMethodTitleLabel]                          NVARCHAR (100)  NULL,
    [PaymentMethodBackLabel]                           NVARCHAR (25)   NOT NULL,
    [PaymentMethodNextLabel]                           NVARCHAR (25)   NOT NULL,
    [ThankYouPageTitleLabel]                           NVARCHAR (100)  NULL,
    [ContactInformationStepLabel]                      NVARCHAR (100)  NOT NULL,
    [ContactInformationTitleLabel]                     NVARCHAR (100)  NULL,
    [ContactInformationBackLabel]                      NVARCHAR (25)   NOT NULL,
    [ContactInformationNextLabel]                      NVARCHAR (25)   NOT NULL,
    [ContactInformationRequiredLabel]                  NVARCHAR (100)  NOT NULL,
    [ContactInformationStringLengthLabel]              NVARCHAR (100)  NOT NULL,
    [ContactInformationShippingLabelsUseBillingLabels] BIT             CONSTRAINT [DF_ContactInformationShippingLabelsUseBillingLabels] DEFAULT ((0)) NOT NULL,
    [PurchaseStepLabel]                                NVARCHAR (100)  NOT NULL,
    [PurchaseTitleLabel]                               NVARCHAR (100)  NULL,
    [PurchaseBackLabel]                                NVARCHAR (25)   NOT NULL,
    [PurchaseNextLabel]                                NVARCHAR (25)   NOT NULL,
    [PurchaseStepVisible]                              BIT             NOT NULL,
    [PurchaseUpdateLabel]                              NVARCHAR (25)   NOT NULL,
    [PurchaseRemoveLabel]                              NVARCHAR (25)   NOT NULL,
    [PaymentMethodLabelsUseBillingLabels]              BIT             CONSTRAINT [DF_PaymentMethodLabelsUseBillingLabels] DEFAULT ((0)) NOT NULL,
    [PaymentMethodDefaultLabel]                        NVARCHAR (25)   CONSTRAINT [DF_PaymentMethodDefaultLabel] DEFAULT ('Default') NOT NULL,
    [PaymentMethodSharedLabel]                         NVARCHAR (25)   CONSTRAINT [DF_PaymentMethodSharedLabel] DEFAULT ('Shared') NOT NULL,
    [PaymentMethodReplaceDefaultLabel]                 NVARCHAR (100)  CONSTRAINT [DF_PaymentMethodReplaceDefaultLabel] DEFAULT ('Replace the default payment method') NOT NULL,
    [PaymentMethodReplaceAddressLabel]                 NVARCHAR (255)  CONSTRAINT [DF_PaymentMethodReplaceAddressLabel] DEFAULT ('Enter different billing information') NULL,
    [PaymentMethodCvvHintLabel]                        NVARCHAR (100)  CONSTRAINT [DF_PaymentMethodCvvHintLabel] DEFAULT ('(3 digits on back of card, AMEX: 4 digits on front)') NOT NULL,
    [PaymentMethodCreditCardLabel]                     NVARCHAR (50)   CONSTRAINT [DF_PaymentMethodCreditCardLabel] DEFAULT ('Credit Card') NOT NULL,
    [PaymentMethodBankAccountLabel]                    NVARCHAR (50)   CONSTRAINT [DF_PaymentMethodBankAccountLabel] DEFAULT ('Bank Account') NOT NULL,
    [PaymentMethodNoneLabel]                           NVARCHAR (50)   CONSTRAINT [DF_PaymentMethodNoneLabel] DEFAULT ('None') NOT NULL,
    [PlanSelectionDescription]                         NVARCHAR (2000) NULL,
    [PlanConfigurationDescription]                     NVARCHAR (2000) NULL,
    [PurchaseDescription]                              NVARCHAR (2000) NULL,
    [ContactInformationDescription]                    NVARCHAR (2000) NULL,
    [PaymentMethodDescription]                         NVARCHAR (2000) NULL,
    [PaymentMethodExistingDescription]                 NVARCHAR (2000) NULL,
    [CheckoutDescription]                              NVARCHAR (2000) NULL,
    [UseInvoiceTemplateLabelsForCheckoutLabels]        BIT             CONSTRAINT [DF_UseInvoiceTemplateLabelsForCheckoutLabels] DEFAULT ((0)) NOT NULL,
    [ChargeDescriptionLabel]                           NVARCHAR (100)  CONSTRAINT [DF_ChargeDescriptionLabel] DEFAULT ('Description') NOT NULL,
    [ChargeQuantityLabel]                              NVARCHAR (100)  CONSTRAINT [DF_ChargeQuantityLabel] DEFAULT ('Quantity') NOT NULL,
    [ChargeUnitPriceLabel]                             NVARCHAR (100)  CONSTRAINT [DF_ChargeUnitPriceLabel] DEFAULT ('Unit Price') NOT NULL,
    [ChargeAmountLabel]                                NVARCHAR (100)  CONSTRAINT [DF_ChargeAmountLabel] DEFAULT ('Amount') NOT NULL,
    [ChargeChargesLabel]                               NVARCHAR (100)  CONSTRAINT [DF_ChargeChargesLabel] DEFAULT ('Charges') NOT NULL,
    [ChargeDiscountLabel]                              NVARCHAR (100)  CONSTRAINT [DF_ChargeDiscountLabel] DEFAULT ('Discount') NOT NULL,
    [ChargeSubtotalLabel]                              NVARCHAR (100)  CONSTRAINT [DF_ChargeSubtotalLabel] DEFAULT ('Subtotal') NOT NULL,
    [ChargeTaxLabel]                                   NVARCHAR (100)  CONSTRAINT [DF_ChargeTaxLabel] DEFAULT ('Tax') NOT NULL,
    [ChargeTotalLabel]                                 NVARCHAR (100)  CONSTRAINT [DF_ChargeTotalLabel] DEFAULT ('Total') NOT NULL,
    [PlanSelectionStepVisible]                         BIT             CONSTRAINT [DF_PlanSelectionStepVisible] DEFAULT ((1)) NOT NULL,
    [PaymentMethodSurchargingLabel]                    VARCHAR (500)   CONSTRAINT [DF_PaymentMethodSurchargingLabel] DEFAULT ('To cover the cost of credit card acceptance, we pass on a 3.5% credit card fee. This fee is not more than the cost of accepting these cards. There is no fee for debit cards.') NOT NULL,
    [CreditCardFeeLabel]                               VARCHAR (50)    CONSTRAINT [DF_CreditCardFeeLabel] DEFAULT ('Credit Card Fee') NOT NULL,
    CONSTRAINT [PK_HostedPageManagedOfferingLabel] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (FILLFACTOR = 100),
    CONSTRAINT [FK_HostedPageManagedOfferingLabel_HostedPageManagedOffering] FOREIGN KEY ([Id]) REFERENCES [dbo].[HostedPageManagedOffering] ([Id])
);


GO

